### ISSUE TITLE
Spike to replace react-proxy

### ISSUE THREAD

**Issue by theKashey** [theKashey/react-stand-in#1]
@neziro - this is mostly for you.
So. What problem we had - in pure ES6/7 environment:
1. Arrow functions are just not working due to wrong `this`.
2. Babel plugin may do something quite wrong.

Solution:
 Step 1 - disable babel magic. At all. Keep only the `register` function.
 Step 2 - try to create workaround, to make RHL work again.
 Step 3 - modify RHL to fix all the things..

Step 1. 
  Simple remove half of babel plugin. All related to the "Class" traverse.

Step 2.
 Create react-stand-in, based on react-proxy. Also - just remove 90% code, and change the root logic.
 As long it is 99% incompatible to the assessor - it is easy to create a separate repo.

How it work.
 It creates a single class, by extending the original and _never_ change or fake `this` in the future.
 It just uses JS core feature - prototype chain.
 `` when you want to update a component - you just change your ancestor ``

```js
Object.setPrototypeOf(ProxyComponent.prototype, NextComponent.prototype);
```
And this is covering 99% cases for 99% code. Without any `real` proxy, which just duplicate the core functionality.
All cases except inability to call constructor, and repeat code, might be hidden inside it.

 Step 3 - Whats left?
1. As long arrow functions are moved to the constructor, it is just impossible to regenerate them. But it is possible to detect the change (https://github.com/theKashey/react-stand-in/blob/master/src/createClassProxy.js#L34) and do something.
Currently - just display an error.
In Future - patch RHL's babel plugin, to add magic method to a class declaration
```js
  class { 
   ....
 __RHL_MAGIC_INSERT(key,data){ this[key]=eval(data); }  // yep! Eval. Must be in the same scope.
 }
```
Next - it will be possible to regenerate bound methods.
```js
 const inst = new NextComponent();
 ThisProxyGeneration.injectOnRender( that => that.__RHL_MAGIC_INSERT(arrowMethod,arrowMethod.toString())
```
Something similar can be done for bound methods - it is possible to detect that method is bound( or via undefined prototype, or one can patch Function.bind :) ), and regenerate them on render.
Unfortunately it requires different approaches, but look like one could deprecate `.bind` as `obsolete`.
Actually - the problem is with the new code, not the old.

PS: It is not always easy to understand me. Just for you information.

**Comment by theKashey** [comment]
Patch for RHL -> https://github.com/theKashey/react-hot-loader/blob/master/src/babel/index.js

**Comment by gregberge** [comment]
@theKashey seems great!

The approach looks cleaner and simpler. 

It tried to run test but it is not passing, is it normal?

**Comment by theKashey** [comment]
@neoziro - yes. That's normal. Half of the tests are not applicable to the new approach, half - just require small rewiring.
Need few more iterations to complete.

**Comment by theKashey** [comment]
@neoziro - tests are green, and the solution was tested both for ES6 and ES5 environment.
Will not without a proper version of RHL:
1. ES6 need Injected by RHL/babel plugin `__facade__regenerateByEval`, to update arrow functions
2. ES5 need injected by RHL/babel plugin `__facade__rewireSuper`, to update superclass "expected" by babel polyfills.

The only "big" issue right now – solution cant handle update _old style_ bound function. It just cant detect changes and reproduce.
But, anyway, the whole idea was to support new ES, not the old one.

**Comment by gregberge** [comment]
OK good, what do you mean by old style bound function?

**Comment by theKashey** [comment]
bound function == function after bind -> this.onClick = this.onClick.bind(this)

I did not find a way how to detect the source of a bound function, thus could not detect change inside it. 
In the same time I've dropped support for autoBound.

So how it works - I am just creating new instances for the old and new Components, and looking for the changes that were made inside a constructor.

**Comment by theKashey** [comment]
Just for a record
 - is it allowed to completely drop support for _bound_ methods, and ask to run manual-bind-to-arrow from react-codemod.
 - __facade__rewireSuper can be used to solve <Component>.type === Component, by replacing the internal class reference is code ships in ES5. Another approach is a bit tricky, but one can wrap result of createElement by proxy, and return the proxy only for react-dom. Any way to detect the renderer?
 - as mention here(https://github.com/gaearon/react-hot-loader/issues/279#issuecomment-343335049), we should try to detect the changes boundaries and thus limit the update. It will solve most of issues with HOC and decorators. But not all.

**Comment by wmertens** [comment]
I wonder, how about monkey-patching `.bind` for all class methods?

So, to prepare a React class for hot reload, walk its functions and wrap `.bind` with a method that injects necessary logic for RHL?

**Comment by theKashey** [comment]
@wmertens - it is the most `bugless` way, and react-proxy actually doing the same.

**Comment by wmertens** [comment]
ah great… also, if `React.Component` would be doing the monkey patching, then this will also work for decorated classes, right?

**Comment by theKashey** [comment]
Nope :)
`Patching` components, to remove tree update is just one part of the work. The second part is to find pairs to swap, and react-hot-loader doing it.
If you will decorate class, compose class, instance it inside HOC, .... - react-hot-loader will be unable to understand what to do, it will not found any similarity between `something` and `something`.
